sudo: required
dist: trusty
language: python

branches:
  except:
    - gh-pages

python:
  - 2.7
  - 3.4
  #- pypy
  #- pypy3

env:
  # This will check any ROS distro supported on this OS
  - DISTRO=indigo
  - DISTRO=jade

# This is the same for all builds
before_install:
  # Install ROS. We always need it on system.
  - bash rosutils/install_ros.sh
  # Install package ROS dependencies (needed until we can package a standard python deb for pyros-setup. see https://github.com/asmodehn/pyros-setup/issues/16)
  - rosdep install --default-yes --from-paths ./ --rosdistro $DISTRO

install:
  - pip install tox tox-travis

script:
  - tox

notifications:
  email: false
